; IN THIS PROGRAM WE HAVE A VALUE FFH AND WE WANT TO SEND THIS TO 15 RAM LOCATIONS STARTING 
;FROM THE FEH ONWARDS

------------------------>>>>>>>>>>>>  SEND THE DATA FFH TO 15 RAM LOCATIONS STARTING AT FE<<<<<<<<<<<<<------------

;We have used indirect adressing mode here

ORG 0X000

COUNTER EQU 0X40

MOVLW 0X15

MOVWF COUNTER

MOVLW 0XFE;
MOVWF FSR

HERE:
MOVLW 0XFF
MOVWF INDF

INCF FSR,F
DECFSZ COUNTER,F
GOTO HERE

END

